### ISSUE TITLE
Unable to upload images with Riiif in Docker

### ISSUE THREAD

**Issue by KingNoah** [curationexperts/riiif#135]
I work at UT Austin, we're running into issues trying to upload single items and CSVs in our Docker containerized Spotlight instance. We're using ImageMagick 6.7.8-9, Riiif 2.3.0, and Spotlight 3.0.0.0.alpha.9. The images are being uploaded into `/public/uploads/spotlight/featured_image/image` and I have added the following to `config/initializers/riiif.rb`:

`Riiif::Image.file_resolver.base_path = '/public/uploads/spotlight/featured_image/image/'`

I get the following in the terminal when it errors out

`Spotlight::FeaturedImage Load (35.9ms)  SELECT  'spotlight_featured_images'.* FROM 'spotlight_featured_images' WHERE 'spotlight_featured_images'.'id' = 12 LIMIT 1`

`[ActiveJob] [Spotlight::ReindexJob] [690846dd-91ce-4145-9369-229372a7b4b6]   ↳ /usr/local/rvm/gems/ruby-2.6.5/gems/activerecord-5.2.4.2/lib/active_record/log_subscriber.rb:98`

`[ActiveJob] [Spotlight::ReindexJob] [690846dd-91ce-4145-9369-229372a7b4b6] Invalid characters in id '12'`

`[ActiveJob] [Spotlight::ReindexJob] [690846dd-91ce-4145-9369-229372a7b4b6] Error performing Spotlight::ReindexJob (Job ID: 690846dd-91ce-4145-9369-229372a7b4b6) from Inline(default) in 328.86ms: Riiif::ImageNotFoundError (Riiif::ImageNotFoundError):`

`/usr/local/rvm/gems/ruby-2.6.5/gems/riiif-2.3.0/app/resolvers/riiif/abstract_file_system_resolver.rb:18:in 'path'`

`/usr/local/rvm/gems/ruby-2.6.5/gems/riiif-2.3.0/app/resolvers/riiif/abstract_file_system_resolver.rb:11:in 'find'`

`/usr/local/rvm/gems/ruby-2.6.5/gems/riiif-2.3.0/app/models/riiif/image.rb:33:in 'file'`

`/usr/local/rvm/gems/ruby-2.6.5/gems/riiif-2.3.0/app/models/riiif/image.rb:53:in 'info'`

We have no problem uploading images locally, outside the container, using the same versions of ImageMagick, Riiif, and Spotlight. Any advice would be greatly appreciated!

**Comment by KingNoah** [comment]
Solved the problem by using Puma app server instead of Passenger
