### ISSUE TITLE
failing tests on master

### ISSUE THREAD

**Issue by jrochkind** [curationexperts/riiif#64]
~~~
  1) Riiif::ImagesController#show sends images to the service
     Failure/Error: expect(response.headers['Cache-Control']).to eq 'max-age=31557600, private'

       expected: "max-age=31557600, private"
            got: "max-age=31556952, private"

       (compared using ==)
     # ./spec/controllers/riiif/images_controller_spec.rb:21:in `block (3 levels) in <top (required)>'

  2) Riiif::ImagesController info returns info
     Failure/Error: expect(response.headers['Cache-Control']).to eq 'max-age=31557600, private'

       expected: "max-age=31557600, private"
            got: "max-age=31556952, private"

       (compared using ==)
     # ./spec/controllers/riiif/images_controller_spec.rb:119:in `block (3 levels) in <top (required)>'
~~~

**Comment by jrochkind** [comment]
I am trying to debug, including going into the Rails source, and I can't figure out what's going on. In some places in Rails `1.year.to_i` is `31556952`, in others it's `31557600`.  Maybe depends on whether it's time-zone aware, taking account of leap seconds or leap days in the current year, or something? 

I suspect a bug in Rails of some kind.
